cat jqxcore.js > jqxgridall.js
cat jqxdata.js >> jqxgridall.js
cat jqxbuttons.js >> jqxgridall.js
cat jqxscrollbar.js >> jqxgridall.js
cat jqxmenu.js >> jqxgridall.js
cat jqxlistbox.js >> jqxgridall.js
cat jqxdropdownlist.js >> jqxgridall.js
cat jqxgrid.js >> jqxgridall.js
cat jqxgrid.selection.js >> jqxgridall.js
cat jqxgrid.columnsresize.js >> jqxgridall.js
cat jqxgrid.filter.js >> jqxgridall.js
cat jqxgrid.sort.js >> jqxgridall.js
cat jqxgrid.pager.js >> jqxgridall.js
cat jqxgrid.grouping.js >> jqxgridall.js